[package]
description = "Ethcore Trusted Signer"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "ethcore-signer"
version = "1.4.0"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rand = "0.3.14"
jsonrpc-core = "2.1"
log = "0.3"
env_logger = "0.3"
ws = { git = "https://github.com/wdv4758h/ws-rs.git", branch = "mio-upstream-stable" }
ethcore-util = { path = "../util" }
ethcore-io = { path = "../util/io" }
ethcore-rpc = { path = "../rpc" }
parity-dapps-signer = { git = "https://github.com/ethcore/parity-ui.git", version = "1.4", optional = true}

clippy = { version = "0.0.82", optional = true}

[features]
dev = ["clippy"]
ui = ["parity-dapps-signer"]
use-precompiled-js = ["parity-dapps-signer/use-precompiled-js"]
